[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "function-calling"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
    "transformers",
    "torch",
    "fire",
    "sentence-transformers",
    "accelerate",
    "wordfreq"
]

[tool.hatch.build.targets.wheel]
packages = ["src"]